### PR TITLE
Merge institutions#new_from_invite_data into institutions#new

### LINKED ISSUE #1467: Alert that invitation has already been accepted instead of crashing
We don't properly handle the case where an invitation has already been accepted, which results in a MissingTemplate exception, reported to the user as a 500 Internal Server Error. We should instead report the actual error with an alert message such as "Error: this invitation has already been accepted. You can login to access your institution".

Follow up on these comments:
- https://github.com/instedd/cdx/pull/1458#pullrequestreview-880427158
- https://github.com/instedd/cdx/pull/1458#discussion_r805736422

### PR DESCRIPTION
**Pull request by ysbaddaden**
Refactor of pending institution invite in institutions controller. Properly takes care of pending and accepted invites (or no invite), with an error flash message when the invitate has already been accepted, and a redirection when the invite can't be found.

closes #1467

### CODE REVIEW

File: app/controllers/institutions_controller.rb [hunk 1]
```diff
@@ -112,30 +100,21 @@ def no_data_allowed
...
   end
 
   private
 
-  def accept_pending_invite
-    if @pending_invite && current_user.email == @pending_invite.invited_user_email
-      @pending_invite.status = 'accepted'
-      @pending_invite.save!
+  def load_pending_invite!
+    return unless id = params[:institution] ? params[:institution][:pending_institution_invite_id] : params[:pending_institution_invite_id]
```
Comment (straight-shoota) [inline app/controllers/institutions_controller.rb:112]: There's so much in this line... what about this instead:
```suggestion
    id = params.dig(:institution, :pending_institution_invite_id) || params[:pending_institution_invite_id] || return
```

**Review by straight-shoota — APPROVED** [review]
❤️

File: app/controllers/institutions_controller.rb (hunk 1 above)
Comment (ysbaddaden) [reply app/controllers/institutions_controller.rb:112]: I thought of `#dig` but we need Ruby 2.3, or the patch from the rails5 upgrade, or I can just use the custom `#get_in` method we currently have (then replace for `#dig` when rebasing the rails5 branch).
