### PR TITLE
Allow to download CSV template file and style fixes

### LINKED ISSUE #1812: Allow to download csv template file
As specified in [this](https://projects.invisionapp.com/d/#/console/4103589/470792644/preview) mockup

### LINKED ISSUE #1833: Align the "Add file" button on the upload results form

### PR DESCRIPTION
**Pull request by leandroradusky**
Closes #1812 & #1833

The link to download a CSV template file was added to the upload sample's results form. 

image

Since this "row" was added for the button, I've added as well the number of files uploaded, which was in the [mockup](https://projects.invisionapp.com/d/main#/console/4103589/470792644/preview) but not implemented. This fixed the alignment of the form and fixes #1833 in addition since is this "row" which is aligned with the "RESULTS" label.

image

Also, to make the template CSV more understandable, a header row is now required when uploading results, containing `sample_UUID` & `measured_signal` column names. The code to support the headers was defined. 

The template file was added to the `public` folder to be served as a static file. Is this OK?

### CODE REVIEW

File: app/controllers/samples_controller.rb [hunk 1]
```diff
@@ -214,7 +214,7 @@ def bulk_process_csv
       CSV.open(csv_file.path) do |csv_stream|
         csv_stream.each do |row|
           sample_id, measured_signal = row[0], row[1]
-
+          next if sample_id == "sample_UUID" # skip header row
```
Comment (ysbaddaden) [inline app/controllers/samples_controller.rb:217]: It might be better to check whether it's an UUID string with a simple regexp.

File: app/views/samples/_upload_results_js.haml [hunk 2]
```diff
@@ -47,7 +50,7 @@
                 var samples = [] // samples uuids
 
                 lines.forEach(function(line) { 
-                    if (line != ''){
+                    if (line != '' && line.split(',')[0] != "sample_UUID"){
```
Comment (ysbaddaden) [inline app/views/samples/_upload_results_js.haml:53]: Same here.

File: app/views/samples/upload_results.haml [hunk 3]
```diff
@@ -13,14 +13,23 @@
...
       %label Results
     .col
-      #uploaded-files
-
+      .row.samples-row
+        .col
+          .text-bold#file-count
+            0 files
+        .col.align-right
+          =link_to '/template.csv', target: "_blank" do
```
Comment (ysbaddaden) [inline app/views/samples/upload_results.haml:21]: We might want a better name. For example a `templates` directory with a `upload_samples_results.csv` file.

**Review by ysbaddaden — CHANGES_REQUESTED** [review]
A few tweaks and it's good to go.

Static files can be in the `public/` folder. This is what the directory is here for.

File: app/controllers/samples_controller.rb (hunk 1 above)
Comment (leandroradusky) [reply app/controllers/samples_controller.rb]: While in javascript I re-used 

`/^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$/gi`

the `g` option didn't worked on ruby and I had to go with 

`/^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$/i`

I get a `SyntaxError ((irb):11: unknown regexp option - g)` 

It should work well in any case, just mentioning it

**Review by ysbaddaden — APPROVED** [review]
